// Executive Advisor — audit log helper.
//
// Writes one document per AI advisor mode invocation to the
// `aiAdvisorInvocations` Firestore collection. The endpoint is the
// only caller; writes are server-side only via the admin SDK so no
// client write surface is exposed.
//
// Posture (do not relax in V1):
//   - Server-only writes via the admin SDK. Firestore rules
//     additionally block any client-side write to this collection.
//   - Reads are admin / instructor only (see firestore/rules.txt).
//   - Stored fields are minimal metadata. Specifically NEVER stored:
//       * full prompt text
//       * raw provider response
//       * Firebase tokens
//       * unrelated student writing content
//       * private profile fields (address, phone, demographics)
//   - sourceIds are stored as id arrays only when present, never
//     resolved to titles or excerpts.
//   - When writes fail (network blip, permissions misconfigured),
//     the helper logs the failure server-side and returns gracefully.
//     A failed audit write does NOT cancel the user's invocation —
//     the chief still sees their advisor response. This is a
//     deliberate tradeoff: visibility into usage is "best effort"
//     in V1; safety guardrails are in the endpoint and the safety
//     scan, not in this audit log.

import { adminDb } from '~~/server/utils/admin'
import type { SourceIds } from './actionCard'
import type { AdvisorMode as CoachAdvisorMode } from '~~/app/types/executiveAdvisor'

export interface AdvisorInvocationCreateInput {
  /** Stable id for this invocation. Generated by the endpoint and
   *  used to correlate any later acceptedAction append (Pass 2). */
  invocationId: string
  /** Mode the chief invoked. V1 (track 4A) modes plus the V2
   *  management-coach modes from app/types/executiveAdvisor.ts. */
  mode:
    | 'daily-command-brief'
    | 'whats-next'
    | 'run-the-meeting'
    | 'assign-the-work'
    | CoachAdvisorMode
  /** Prompt template version that produced the response. */
  templateVersion: string
  invokedBy: { uid: string; displayName: string; role: string; email: string }
  /** ISO timestamp the endpoint started handling the request. */
  invokedAt: string
  /** Length in characters of the assembled prompt (system + user).
   *  ~4 chars/token gives instructors a rough cost signal without
   *  storing the prompt itself. */
  contextPackageSizeChars: number
  /** Whether the response passed schema validation. */
  responseValidated: boolean
  /** Whether the personal-judgment scan passed. False indicates the
   *  endpoint rejected the response and did NOT charge the chief's
   *  daily quota. */
  safetyScanPassed: boolean
  /** Aggregate counts of source IDs that appeared across action
   *  cards / signal references in the response. NOT the IDs
   *  themselves — counts only — so the audit collection stays
   *  small and never carries grounding data that could be
   *  reconstructed offline. */
  sourceCounts?: {
    taskIds: number
    deliverableIds: number
    sectionIds: number
    requirementIds: number
    advisorSignalIds: number
  }
}

export interface AcceptedActionAppendInput {
  invocationId: string
  /** Action card id from the original AI response. */
  actionId: string
  /** Action type — V1 only knows task creation; future modes can
   *  add types ("returned-with-feedback", etc.) when Track 4B
   *  ships. */
  actionType: 'task-created'
  /** ISO timestamp of acceptance. */
  acceptedAt: string
  /** Firestore task doc id created from this action card. */
  createdTaskId: string
}

const COLLECTION = 'aiAdvisorInvocations'

/**
 * Writes a new invocation document. Server-side only.
 * Returns the same input on success so callers can chain.
 * Logs failures and returns gracefully — the chief should never see
 * a UI error because the audit log was unreachable.
 */
export async function recordInvocation(
  input: AdvisorInvocationCreateInput
): Promise<void> {
  const sourceCounts = input.sourceCounts ?? {
    taskIds: 0,
    deliverableIds: 0,
    sectionIds: 0,
    requirementIds: 0,
    advisorSignalIds: 0
  }
  try {
    const db = adminDb()
    const ref = db.collection(COLLECTION).doc(input.invocationId)
    await ref.set({
      mode: input.mode,
      templateVersion: input.templateVersion,
      invokedBy: input.invokedBy,
      invokedAt: input.invokedAt,
      contextPackageSizeChars: input.contextPackageSizeChars,
      responseValidated: input.responseValidated,
      safetyScanPassed: input.safetyScanPassed,
      sourceCounts,
      // Pass 2 will append `acceptedActions: [...]` when a chief
      // accepts an action card. Initialize empty so that
      // FieldValue.arrayUnion appends work without a follow-up
      // existence check.
      acceptedActions: [],
      createdAt: input.invokedAt
    })
  } catch (e) {
    // Audit logging is best-effort. Log to server console so
    // operators can grep for failures without breaking the chief's
    // experience.
    console.warn(
      '[aiAdvisorInvocations] write failed',
      input.invocationId,
      input.mode,
      e instanceof Error ? e.message : String(e)
    )
  }
}

/**
 * Aggregates source-id counts across an unknown response object.
 * The endpoint runs this on the validated response so the audit log
 * captures grounding intensity without storing the IDs themselves.
 *
 * Two source-id shapes are supported:
 *   V1 ActionCard: `sourceIds: { taskIds?: string[]; deliverableIds?:
 *     string[]; sectionIds?: string[]; requirementIds?: string[];
 *     advisorSignalIds?: string[] }` — the structured SourceIds
 *     object originally introduced for the four V1 modes.
 *   V2 AdvisorActionCard: `sourceIds: string[]` — a flat array of
 *     opaque grounding IDs. Each string is classified into a
 *     bucket via prefix heuristics that match what the V2 context
 *     and prompt produce. Strings whose bucket cannot be inferred
 *     fall back to `taskIds` (the most common ID type in scope).
 */
export function countSourceIds(value: unknown): {
  taskIds: number
  deliverableIds: number
  sectionIds: number
  requirementIds: number
  advisorSignalIds: number
} {
  const counts = {
    taskIds: 0,
    deliverableIds: 0,
    sectionIds: 0,
    requirementIds: 0,
    advisorSignalIds: 0
  }
  visit(value)
  return counts

  function visit(node: unknown): void {
    if (node === null || node === undefined) return
    if (Array.isArray(node)) {
      for (const child of node) visit(child)
      return
    }
    if (typeof node !== 'object') return
    const obj = node as Record<string, unknown>
    if ('sourceIds' in obj) {
      countSourceIdsField(obj.sourceIds, counts)
    }
    for (const child of Object.values(obj)) visit(child)
  }
}

/** Mutates `counts` to add the contribution of one `sourceIds`
 *  field. Handles both the V1 structured object shape and the V2
 *  flat string array shape. */
function countSourceIdsField(
  field: unknown,
  counts: {
    taskIds: number
    deliverableIds: number
    sectionIds: number
    requirementIds: number
    advisorSignalIds: number
  }
): void {
  if (field === null || field === undefined) return
  // V2 shape — flat string array, classify each entry by prefix.
  if (Array.isArray(field)) {
    for (const id of field) {
      if (typeof id !== 'string') continue
      classifyV2SourceId(id, counts)
    }
    return
  }
  // V1 shape — structured object with named arrays.
  if (typeof field === 'object') {
    const s = field as SourceIds
    counts.taskIds += s.taskIds?.length ?? 0
    counts.deliverableIds += s.deliverableIds?.length ?? 0
    counts.sectionIds += s.sectionIds?.length ?? 0
    counts.requirementIds += s.requirementIds?.length ?? 0
    counts.advisorSignalIds += s.advisorSignalIds?.length ?? 0
  }
}

/** Classifies one V2 sourceId string into a counts bucket via
 *  deterministic prefix matching. The prefixes mirror the IDs the
 *  V2 advisor context and the project-navigator signal helper
 *  emit, so the audit count reflects the model's actual grounding
 *  intensity. Unknown strings fall back to `taskIds` (the most
 *  common opaque-Firestore-ID shape in scope). */
function classifyV2SourceId(
  id: string,
  counts: {
    taskIds: number
    deliverableIds: number
    sectionIds: number
    requirementIds: number
    advisorSignalIds: number
  }
): void {
  // Project Navigator signals — emitted by buildProjectNavigatorSignals.
  if (id.startsWith('blocked-task:')) {
    counts.taskIds += 1
    return
  }
  if (
    id.startsWith('overdue-deliverable:') ||
    id.startsWith('ready-for-review:') ||
    id.startsWith('needs-revision:') ||
    id.startsWith('missing-final-output:')
  ) {
    counts.deliverableIds += 1
    return
  }
  if (id.startsWith('missing-dependency:')) {
    counts.advisorSignalIds += 1
    return
  }
  // Final-week lane entry id format: `ch-XX:section-id`.
  // The colon distinguishes section refs from raw chapter ids.
  if (id.startsWith('ch-') && id.includes(':')) {
    counts.sectionIds += 1
    return
  }
  // Bare chapter id (e.g. `ch-08-finance-and-revenue-model`).
  if (id.startsWith('ch-')) {
    counts.deliverableIds += 1
    return
  }
  // Default — opaque Firestore IDs are most often task IDs in the
  // V2 advisor scope. Counted into `taskIds` so the audit row
  // reflects grounding intensity rather than dropping the ID.
  counts.taskIds += 1
}
